#ifndef PHANTOM_AOA_FLAG_H
#define PHANTOM_AOA_FLAG_H

enum class Flag {
    NOSE_WHEEL_EXTENDED,
    WEIGHT_ON_WHEEL,
    GEAR_EXTENDED,
    SLATS_IN,
    AGM_45_SELECTED,
    FROZEN_AOA_SENSOR
};

#endif //PHANTOM_AOA_FLAG_H
